name: Build VeraPDF Native Binary

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          version: 'latest'
          java-version: '21'
          distribution: 'graalvm-community'
          # components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Maven
        run: |
          sudo apt update
          sudo apt install -y maven

      - name: Checkout VeraPDF apps
        uses: actions/checkout@v4
        with:
          repository: 'veraPDF/veraPDF-apps'
          path: 'veraPDF-apps'

      - name: Run tests
        run: |
          cd veraPDF-apps
          mkdir -p native-config
          mvn -DargLine="-agentlib:native-image-agent=config-output-dir=$(pwd)/native-config" test

      - name: Build VeraPDF CLI JAR
        run: |
          cd veraPDF-apps
          mvn clean package -DskipTests
          tree
          cp cli/target/cli-*.jar ../verapdf-cli.jar

      - name: Collect Native Image Config via CLI run
        run: |
          java -agentlib:native-image-agent=config-merge-dir=veraPDF-apps/native-config -jar verapdf-cli.jar --version

      - name: Convert JAR to Native Binary
        run: |
          native-image \
            --no-fallback \
            -march=compatibility \
            -H:IncludeResources=".*\\.properties$" \
            -H:ConfigurationFileDirectories=veraPDF-apps/native-config \
            --initialize-at-build-time=javax.xml.bind,com.sun.xml.bind,org.verapdf \
            -jar verapdf-cli.jar \
            verapdf-native

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: verapdf-native-linux
          path: verapdf-native

      # - name: Build from standalone
      #   run: |
      #     wget https://github.com/user-attachments/files/19467374/app.zip
      #     unzip app.zip
      #     native-image --no-fallback -march=compatibility -jar app.jar verapdf-cli-native

      # - name: Upload Artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: verapdf-cli-native-linux
      #     path: verapdf-cli-native
